name: Makefile CI

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      with:
        arch: aarch64
        run: sudo apt-get install -y libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf llvm binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: configure
      with:
        arch: aarch64
        run: make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- defconfig

    - name: build Image
      with:
        arch: aarch64      
        run: make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image -j16

    - name: build DTB
      with:
        arch: aarch64      
        run: make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbs -j16

    - name: build modules
      with:
        arch: aarch64        
        run: make -j15 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules
